# Generated by Django 4.2.4 on 2023-08-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Enter text of the post', verbose_name='Text of the post'),
        ),
    ]
